version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: angular_dev  # Nombre consistente
    volumes:
      - ./frontend/dist/browser:/usr/share/nginx/html
    networks:
      - devnet

  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_dev
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=dev  # Cambiado a dev para diferenciar
      - APP_SECRET=ChangeThisSecret
      - DATABASE_URL=mysql://symfony:password@mysql:3306/app_db?serverVersion=5.7
    depends_on:
      - mysql
    networks:
      - devnet

  mysql:
    image: mysql:5.7
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devnet

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_dev
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/browser:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - devnet

volumes:
  mysql_data:

networks:
  devnet:
    driver: bridge
