services:
  frontend:
    build:
      context: ./frontend
    container_name: angular_prod
    volumes:
      - ./frontend/dist/browser:/usr/share/nginx/html
    networks:
      - prodnet

  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_prod
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=prod
      - APP_SECRET=ChangeThisSecret
      - DATABASE_URL=mysql://symfony:password@mysql:3306/app_db?serverVersion=5.7
    depends_on:
      - mysql
    networks:
      - prodnet

  mysql:
    image: mysql:5.7
    container_name: mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data_prod:/var/lib/mysql
    networks:
      - prodnet

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_prod
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/browser:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - prodnet

volumes:
  mysql_data_prod:

networks:
  prodnet:
    driver: bridge
