name: Deploy Production

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker/**'
      - '.github/workflows/deploy.yml'
      - 'docker-compose.prod.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and deploy
        run: |
          # Variables
          export DOCKER_IMAGE=tuusuario/dogs-infra
          export VERSION=$(date +%Y%m%d%H%M%S)

          # Build Angular
          cd frontend
          npm ci
          npm run build -- --configuration=production
          cd ..

          # Build Docker images
          docker-compose -f docker-compose.prod.yml build
          
          # Push images (opcional)
          docker tag proyecto-devops-backend $DOCKER_IMAGE-backend:$VERSION
          docker tag proyecto-devops-frontend $DOCKER_IMAGE-frontend:$VERSION
          docker push $DOCKER_IMAGE-backend:$VERSION
          docker push $DOCKER_IMAGE-frontend:$VERSION

          # Deploy (ejemplo para servidor SSH)
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /opt/dogs-infra &&
            git pull &&
            docker-compose -f docker-compose.prod.yml up -d --build
          "
